name: subiquity_client
description: Subiquity Client
version: 0.0.1
homepage: https://github.com/canonical/ubuntu-desktop-installer

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  http: ^0.12.2

dev_dependencies:
  pedantic: ^1.9.0
  flutter_test:
    sdk: flutter
