name: subiquity_client
description: Subiquity Client
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  tuple:

dev_dependencies:
  pedantic: ^1.9.0
  flutter_test:
    sdk: flutter
