name: Windows WSL Setup CI

on:
  push:
    branches:
      - main
    paths:
      - packages/subiquity_client/**
      - packages/ubuntu_wizard/**
      - packages/ubuntu_wsl_setup/**
      - .github/workflows/**
  pull_request:
    branches:
      - main
    paths:
      - packages/subiquity_client/**
      - packages/ubuntu_wizard/**
      - packages/ubuntu_wsl_setup/**
      - .github/workflows/**      
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable'

    - name: Install Melos
      run: flutter pub global activate melos

    - name: Bootstrap workspace
      shell: powershell
      run: |
# Bootstrapping is a file system intensive operation, which seems to recycle
# some temporary file names. Windows is known for file system race conditions
# when deleting or renaming files, so running melos just once will likely fail.
        Invoke-Command -ErrorAction 'Ignore' -ScriptBlock {melos bootstrap}
        melos bootstrap

    - name: Build Windows Target
      working-directory: packages\ubuntu_wsl_setup\
      run: flutter build -t .\lib\main_win.dart
