name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v1
    - uses: subosito/flutter-action@v1
      with:
        channel: 'dev'

    - name: Enable Linux desktop support
      run: flutter config --enable-linux-desktop

    # subiquity_client
    
    - name: Get subiquity_client dependencies
      working-directory: ./subiquity_client
      run: flutter pub get
    
    - name: Check for any formatting issues in subiquity_client
      working-directory: ./subiquity_client
      run: flutter format --set-exit-if-changed .
    
    - name: Statically analyze subiquity_client for any errors
      working-directory: ./subiquity_client
      run: flutter analyze .
    
    - name: Run tests on subiquity_client
      working-directory: ./subiquity_client
      run: flutter test

    # ubuntu_desktop_installer

    - name: Get ubuntu_desktop_installer dependencies
      working-directory: ./ubuntu_desktop_installer
      run: flutter pub get
    
    - name: Check for any formatting issues in ubuntu_desktop_installer
      working-directory: ./ubuntu_desktop_installer
      run: flutter format --set-exit-if-changed .
    
    - name: Statically analyze ubuntu_desktop_installer for any errors
      working-directory: ./ubuntu_desktop_installer
      run: flutter analyze .
    
    - name: Run tests on ubuntu_desktop_installer
      working-directory: ./ubuntu_desktop_installer
      run: flutter test
